# Generated by Django 5.0.3 on 2024-03-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
