# Generated by Django 5.0.3 on 2024-03-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksAPI', '0002_alter_task_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
